<div class="row login-row">
  <div class="container-login">
    <div class="login-form">
      <h2 class="loginAdm-h2">ACCÈS ADMINISTRATION</h2>
      <form class="loginAdm-form" action="/controllers/LoginController.php" method="post">
        <?php if(isset($errorMessage)) :?>
          <div class="alert alert-danger" role="alert">
          <?= $errorMessage ?>
        </div>
        <?php endif ?>
        <div class="form-group">
          <label for="pseudo">Pseudo</label>
          <input type="text" name="pseudo" id="pseudo" class="form-control">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" id="password" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Connexion</button>
      </form>
    </div>
  </div>
</div>