<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>


    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://kit.fontawesome.com/f821045c00.js" crossorigin="anonymous"></script>
        <!-- HEADER CSS + JS -->
        <link rel="stylesheet" href="/css/header.css">
        <link rel="stylesheet" href="/css/card.css">
        <link rel="stylesheet" href="/css/filter.css">
        <link rel="stylesheet" href="/css/style.css">
        <script src="/js/header.js"></script>
        <title><?= $title ?></title>
    </head>
    <header>
    <?php  if(isset($_SESSION['role']) && $_SESSION['role'] == 'admin') : ?>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <h3 class="navbar-brand">Administration</h3>
            
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/controllers/AdminController.php">Toutes les annonces <span
                        class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/controllers/AddItemController.php">Ajouter une annonce</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/controllers/AdminUserController.php">Utilisateurs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/index.php">Quitter l'administration</a>
                </li>
                </ul>
            </div>
            <div class="alert alert-warning" role="alert">
                <i class="fas fa-exclamation-triangle"></i> ATTENTION ! N'oubliez pas de cliquer sur "Quitter l'administration" lorsque vous terminez.
            </div>
        </nav>
    <?php endif; ?>
    </header>
    <body>
        
        
                
        <div class="container-fluid">
                    <?php 
                    if (isset($template)){
                        include CHEMIN . 'www' . DIRECTORY_SEPARATOR . $template; 
                    }
                    else{
                        echo '<h1>INDEX SANS TEMPLATE</h1>';
                    }
                    ?>
        </div>

        <script src="/js/BuyFilter.js"></script>
        <script src="/js/RentFilter.js"></script>
    </body>
    

</html>
