<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>


    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://kit.fontawesome.com/f821045c00.js" crossorigin="anonymous"></script>
        <!-- HEADER CSS + JS -->
        <link rel="stylesheet" href="/css/header.css">
        <link rel="stylesheet" href="/css/card.css">
        <link rel="stylesheet" href="/css/filter.css">
        <link rel="stylesheet" href="/css/style.css">
        <script src="/js/header.js"></script>
        <title><?= $title ?></title>
    </head>
    <body>
        
        <header id="header">
            <div class="container" id="container-nav">

            <div id="logo" class="pull-left col-md-6">
                <h1><a href="/index.php" class="scrollto">E-MMOBILIER</a></h1>
            </div>

            <nav id="nav-menu-container">
                <ul class="nav-menu">
                <li class="nav-li menu-active"><a class="nav-a" href="/index.php">Accueil</a></li>
                <li class="nav-li"><a class="nav-a" href="/controllers/BuyController.php">Acheter</a></li>
                <li class="nav-li"><a class="nav-a" href="/controllers/SellController.php">Vendre</a></li>
                <li class="nav-li"><a class="nav-a" href="/controllers/RentController.php">Louer</a></li>
                <li class="nav-li"><a class="nav-a" href="/controllers/ContactController.php">Contact</a></li>
                
                
                </ul>
            </nav><!-- #nav-menu-container -->

            </div>
        </header><!-- #header -->
                
        <div class="container-fluid">
                    <?php 
                    if (isset($template)){
                        include CHEMIN . 'www' . DIRECTORY_SEPARATOR . $template; 
                    }
                    else{
                        echo '<h1>INDEX SANS TEMPLATE</h1>';
                    }
                    ?>
        </div>

        <footer>
            <div class="row container container-footer">
                <div class="col-md-3 col-footer">Mentions légales</div>
                <div class="col-md-3 col-footer">CGU</div>
                <div class="col-md-3 col-footer">Nous recrutons</div>
                <div class="col-md-3 col-footer">Agence Principale <br>6 Avenue du Colonel Fabien<br>92340 Argenton</div>
            </div>
            <!-- <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small> -->

        </footer>
        <script src="/js/BuyFilter.js"></script>
        <script src="/js/RentFilter.js"></script>
    </body>
    

</html>
